import { Job, User } from "./types";

export const jobs: Job[] = [
  {
    id: 1,
    title: "Senior Software Engineer",
    company: "TechGlobe Solutions",
    location: "Dubai, UAE",
    requiredAge: 25,
    requiredGender: "All",
    requiredLanguages: ["English", "Arabic"],
    requiredCitizenship: "UAE",
    requiredEmploymentStatus: "Bachelors"
  },
  {
    id: 2,
    title: "Research Scientist",
    company: "BioInnovate Labs",
    location: "Montreal, Canada",
    requiredAge: 28,
    requiredGender: "All",
    requiredLanguages: ["English", "French"],
    requiredCitizenship: "Canadian",
    requiredEmploymentStatus: "PhD"
  },
  {
    id: 3,
    title: "Marketing Director",
    company: "Global Brands Inc",
    location: "Paris, France",
    requiredAge: 30,
    requiredGender: "All",
    requiredLanguages: ["French", "English"],
    requiredCitizenship: "French",
    requiredEmploymentStatus: "Masters"
  },
  {
    id: 4,
    title: "Hotel Manager",
    company: "Luxury Resorts International",
    location: "Abu Dhabi, UAE",
    requiredAge: 35,
    requiredGender: "All",
    requiredLanguages: ["Arabic", "English", "French"],
    requiredCitizenship: "UAE",
    requiredEmploymentStatus: "Bachelors"
  },
  {
    id: 5,
    title: "Healthcare Administrator",
    company: "Metropolitan Medical Center",
    location: "Toronto, Canada",
    requiredAge: 27,
    requiredGender: "All",
    requiredLanguages: ["English", "French"],
    requiredCitizenship: "Canadian",
    requiredEmploymentStatus: "Masters"
  },
  {
    id: 6,
    title: "Construction Project Manager",
    company: "BuildWell Corporation",
    location: "Riyadh, Saudi Arabia",
    requiredAge: 32,
    requiredGender: "Male",
    requiredLanguages: ["Arabic", "English"],
    requiredCitizenship: "Saudi Arabian",
    requiredEmploymentStatus: "Bachelors"
  },
  {
    id: 7,
    title: "Fashion Designer",
    company: "Elegance Fashion House",
    location: "Lyon, France",
    requiredAge: 24,
    requiredGender: "Female",
    requiredLanguages: ["French", "English"],
    requiredCitizenship: "French",
    requiredEmploymentStatus: "Diploma"
  },
  {
    id: 8,
    title: "Data Scientist",
    company: "AI Solutions Ltd",
    location: "Ottawa, Canada",
    requiredAge: 26,
    requiredGender: "All",
    requiredLanguages: ["English"],
    requiredCitizenship: "Canadian",
    requiredEmploymentStatus: "PhD"
  },
  {
    id: 9,
    title: "Arabic Language Instructor",
    company: "International Language Institute",
    location: "Cairo, Egypt",
    requiredAge: 28,
    requiredGender: "All",
    requiredLanguages: ["Arabic", "English"],
    requiredCitizenship: "Egyptian",
    requiredEmploymentStatus: "Masters"
  },
  {
    id: 10,
    title: "Financial Analyst",
    company: "Global Investment Bank",
    location: "Dubai, UAE",
    requiredAge: 25,
    requiredGender: "All",
    requiredLanguages: ["English", "Arabic"],
    requiredCitizenship: "UAE",
    requiredEmploymentStatus: "Masters"
  }
]

export const users: User[] = [
  {
    id: 1,
    firstName: "Sarah",
    lastName: "Mitchell",
    email: "sarah.mitchell@email.com",
    phoneNumber: "+1-555-123-4567",
    gender: "Female",
    languages: ["English", "French"],
    disability: "None",
    age: 29,
    citizenship: "Canadian",
    employmentStatus: "Employed",
    levelOfEducation: "Masters"
  },
  {
    id: 2,
    firstName: "Ahmed",
    lastName: "Hassan",
    email: "ahmed.hassan@email.com",
    phoneNumber: "+971-50-123-4567",
    gender: "Male",
    languages: ["Arabic", "English"],
    disability: "Visual impairment",
    age: 34,
    citizenship: "UAE",
    employmentStatus: "Self-Employed",
    levelOfEducation: "PhD"
  },
  {
    id: 3,
    firstName: "Marie",
    lastName: "Dubois",
    email: "marie.dubois@email.com",
    phoneNumber: "+33-6-12-34-56-78",
    gender: "Female",
    languages: ["French", "English", "Arabic"],
    disability: "None",
    age: 26,
    citizenship: "French",
    employmentStatus: "Employed",
    levelOfEducation: "Bachelors"
  },
  {
    id: 4,
    firstName: "James",
    lastName: "Wilson",
    email: "james.wilson@email.com",
    phoneNumber: "+44-7700-900123",
    gender: "Male",
    languages: ["English"],
    disability: "None",
    age: 41,
    citizenship: "British",
    employmentStatus: "Self-Employed",
    levelOfEducation: "Diploma"
  },
  {
    id: 5,
    firstName: "Fatima",
    lastName: "Al-Sayed",
    email: "fatima.alsayed@email.com",
    phoneNumber: "+20-100-123-4567",
    gender: "Female",
    languages: ["Arabic", "English", "French"],
    disability: "Hearing impairment",
    age: 31,
    citizenship: "Egyptian",
    employmentStatus: "Unemployed",
    levelOfEducation: "Masters"
  },
  {
    id: 6,
    firstName: "Carlos",
    lastName: "Rodriguez",
    email: "carlos.rodriguez@email.com",
    phoneNumber: "+52-1-55-1234-5678",
    gender: "Male",
    languages: ["English", "French"],
    disability: "Mobility impairment",
    age: 38,
    citizenship: "Mexican",
    employmentStatus: "Employed",
    levelOfEducation: "PhD"
  },
  {
    id: 7,
    firstName: "Lisa",
    lastName: "Chen",
    email: "lisa.chen@email.com",
    phoneNumber: "+65-8123-4567",
    gender: "Female",
    languages: ["English", "French"],
    disability: "None",
    age: 27,
    citizenship: "Singaporean",
    employmentStatus: "Self-Employed",
    levelOfEducation: "Masters"
  },
  {
    id: 8,
    firstName: "Alex",
    lastName: "Thompson",
    email: "alex.thompson@email.com",
    phoneNumber: "+1-202-555-0123",
    gender: "All",
    languages: ["English"],
    disability: "None",
    age: 33,
    citizenship: "American",
    employmentStatus: "Employed",
    levelOfEducation: "Bachelors"
  },
  {
    id: 9,
    firstName: "Yuki",
    lastName: "Tanaka",
    email: "yuki.tanaka@email.com",
    phoneNumber: "+81-80-1234-5678",
    gender: "Female",
    languages: ["English"],
    disability: "None",
    age: 29,
    citizenship: "Japanese",
    employmentStatus: "Unemployed",
    levelOfEducation: "Masters"
  },
  {
    id: 10,
    firstName: "Omar",
    lastName: "Ibrahim",
    email: "omar.ibrahim@email.com",
    phoneNumber: "+966-50-123-4567",
    gender: "Male",
    languages: ["Arabic", "English", "French"],
    disability: "None",
    age: 36,
    citizenship: "Saudi Arabian",
    employmentStatus: "Self-Employed",
    levelOfEducation: "Diploma"
  }
]